# This is a basic workflow to help you get started with Actions

name: Prepare Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Current Time
      uses: gerred/current-time@v1.0.0
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
          # Set always-auth in npmrc
          always-auth: false # optional, default is false
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          node-version: 10.x# optional, default is 10.x
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Create surrounding folders
      run: |
        mkdir -p powercord/src/Powercord/plugins
        mv ./grammer-nazi ./powercord/src/Powercord/plugins
        
    - name: Put dependancies into right folder
      run: |
        cd powercord
        mkdir node_modules
        npm i spelling-corrector

    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: release.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: .
    
    - name: Create a Release
      uses: actions/create-release@v1
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: github.GITHUB_REF 
        # The name of the release. For example, `Release v1.0.1`
        release_name: ${{ steps.current-time.outputs.time }}
        # Text describing the contents of the tag.
        body: yeah idk either
        # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: false
        # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        prerelease: true
              
